AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Snowflake Flask Application with Three.js visualizations
  
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        USERNAME: !Ref SnowflakeUsername
        PASSWORD: !Ref SnowflakePassword
        REGION: !Ref SnowflakeRegion

Parameters:
  SnowflakeUsername:
    Type: String
    Description: Snowflake username
    NoEcho: false
  
  SnowflakePassword:
    Type: String
    Description: Snowflake password
    NoEcho: true
  
  SnowflakeRegion:
    Type: String
    Description: Snowflake region
    Default: us-west-1

Resources:
  SnowFlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
        RootRequest:
          Type: Api
          Properties:
            Path: /
            Method: any

Outputs:
  SnowFlaskApi:
    Description: "API Gateway endpoint URL for Prod stage for Snow Flask function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  SnowFlaskFunction:
    Description: "Snow Flask Lambda Function ARN"
    Value: !GetAtt SnowFlaskFunction.Arn
